### ISSUE TITLE
Student view

### ISSUE THREAD

**Issue by mgelbart** [CPSC340/classy#33]
1. It just says "DELIVERABLE SELECT" and doesn't say that the dropdown pertains to teams (until you actually select a deliverable).
2. There's no space between "Your team is" and the team ID.
3. The entire pane pertaining to team selection should not be shown if teams are off (i.e. max size is 1) for all deliverables. 
4. Change "FINAL GRADE" to "OVERALL COURSE GRADE". 
5. Merge two dropdowns into one. This gives you team selection (if applicable - otherwise don't show it) and grades for that deliverable. 
6. When viewing grades for a specific deliverable, need 2 more columns: letter grade (e.g. A+) and scaled score (e.g. 95% for A+) 
7. When viewing grades for a specific deliverable, add a percentage grade for the deliverable.
8. When viewing course grades, let's have the following columns: Item, Weight, Grade (out of 100, to 1 decimal place - i.e. raw/max*100). And then one line below everything showing the final course grade as a percentage.

**Comment by jopika** [comment]
- [x] It just says "DELIVERABLE SELECT" and doesn't say that the dropdown pertains to teams (until you actually select a deliverable).
- [x] There's no space between "Your team is" and the team ID.
- [x] The entire pane pertaining to team selection should not be shown if teams are off (i.e. max size is 1) for all deliverables.
- [x] Change "FINAL GRADE" to "OVERALL COURSE GRADE".
- [x] Merge two dropdowns into one. This gives you team selection (if applicable - otherwise don't show it) and grades for that deliverable.
- [x] When viewing grades for a specific deliverable, need 2 more columns: letter grade (e.g. A+) and scaled score (e.g. 95% for A+)
- [x] When viewing grades for a specific deliverable, add a percentage grade for the deliverable.
- [x] When viewing course grades, let's have the following columns: Item, Weight, Grade (out of 100, to 1 decimal place - i.e. raw/max*100). And then one line below everything showing the final course grade as a percentage.

**Comment by jopika** [comment]
All UI/UX elements have been implemented as of the latest commit in `release/mds`.
